SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS member_sync;

CREATE TABLE member_sync (
    member_id BIGINT NOT NULL PRIMARY KEY,
    nickname VARCHAR(30) NOT NULL,
    profile_image_url VARCHAR(512) NULL,
    sweetness DECIMAL(5,2) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;